# Generated by Django 4.1.9 on 2023-05-22 09:19

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateTimeField(auto_now_add=True)),
                ('outcome', models.FloatField()),
                ('account', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
        ),
    ]
